url: https://yjc-kr.github.io
baseurl: /webpage

# Site settings
title: Yong Jun Choi
email: yongjc@postech.ac.rkr
description: "Personal Blog by Yong Jun Choi"


# Team names, titles and social links
people:
- name: Yong Jun Choi
  pic: 1
  position: Graduate Student
  social:
    - title: linked-in
      url: www.linkedin.com/in/yjc-kr

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/yjc-kr

# Build settings
markdown: kramdown
permalink: pretty
